### ISSUE TITLE
src/JPEGDecoder.cpp

### ISSUE THREAD

**Issue by nopnop2002** [Bodmer/JPEGDecoder#19]
Hello Bodmer.
Thank you for your useful library.

I found wrong code.
Line 348-367

And i use this library.
https://github.com/greiman/SdFat

next code don't work with this library..

File pInFile = SD.open( pFilename, FILE_READ);

Next code work with this library..

File pInFile;
pinFile = SD.open( pFilename, FILE_READ);

`#if defined (LOAD_SD_LIBRARY) || defined (LOAD_SDFAT_LIBRARY)

// Call specific to SD filing system in case leading / is used
int JPEGDecoder::decodeSdFile(const char *pFilename) {

	File pInFile = SD.open( pFilename, FILE_READ);

	return decodeSdFile(pInFile);
}

int JPEGDecoder::decodeSdFile(const String& pFilename) {
#if !defined (ARDUINO_ARCH_SAM)
	File pInFile = SD.open( pFilename, FILE_READ);

	return decodeSdFile(pInFile);
#else
	return -1;
#endif
}`

**Comment by nopnop2002** [comment]
If you can speek Japanese, I can speek too.

**Comment by Bodmer** [comment]
I had a look and cannot see what change you made, also there is an error in your solution code.

pinFile should read pInFile?

What error message do you get with SdFat?

I do not speak Japanese other than the usual greeting!

**Comment by Bodmer** [comment]
I am not sure I understand the problem.  It seems to work for me with Mega and Due.  What processor are you using? What IDE version?

**Comment by nopnop2002** [comment]
I'm using STM32F103 processor.
IDE version is 1.8.5
define LOAD_SDFAT_LIBRARY.

Thank you.

**Comment by anlpereira** [comment]
I'm using the ESP32 Wroon board. It is great. It takes about 300ms to draw a 240x320 Image on an ILI9341 2.8" display. 

https://www.youtube.com/watch?v=1VqzZrW_9JY

**Comment by Bodmer** [comment]
This problem seems to be related to the STM32F103. I have not seen any issues with other boards.
