### ISSUE TITLE
Probably wrong memset

### ISSUE THREAD

**Issue by HumamHelfawi** [Bodmer/JPEGDecoder#24]
https://github.com/Bodmer/JPEGDecoder/blob/628752b7b937074ff6960ab7c57c3a8f0a5d59ae/src/JPEGDecoder.cpp#L437

I was wondering if this line should be:

`memset(pImage , 0 , image_info.m_MCUWidth * image_info.m_MCUHeight * sizeof(*pImage))`

Thanks!

**Comment by Bodmer** [comment]
Thanks, fixed this and associated latent bugs. In practice clearing the array is not necessary.
