### ISSUE TITLE
Not able to display images on ILI9341 240*320 Tft by using ESP8266

### ISSUE THREAD

**Issue by acharyanachiket** [Bodmer/JPEGDecoder#33]
All images are messed up

**Comment by Bodmer** [comment]
If the images look rather psychedelic then it is likely the byte order swap needs to be set in your sketch.

Please identify which example you are trying to run and which graphics library you are using.

**Comment by acharyanachiket** [comment]
uncommented SWAP_BYTES in user_config.h and also used readSwappedBytes() instead of read() still see the images totally blurred(parallel lines). Tried changing the SPI frequency too. 
Sketch used is NodeMCU_Jpeg and TFT I use ILI9341
![baboonl](https://user-images.githubusercontent.com/43720290/51854797-a5a6b580-2351-11e9-888e-6e5db5bd5cb9.jpg)

**Comment by acharyanachiket** [comment]
> If the images look rather psychedelic then it is likely the byte order swap needs to be set in your sketch.
> 
> Please identify which example you are trying to run and which graphics library you are using.

uncommented SWAP_BYTES in user_config.h and also used readSwappedBytes() instead of read() still see the images totally blurred(parallel lines). Tried changing the SPI frequency too.
Sketch used is NodeMCU_Jpeg and TFT I use ILI9341. I amtrying to display BaboonP image here
![bodmer](https://user-images.githubusercontent.com/43720290/52350548-d623d900-2a4e-11e9-9363-145cafcc6e4b.jpg)

**Comment by Bodmer** [comment]
This turned out to be a change made by the Adafruit setAddrWindow() function parameters.

I have updated the library examples for Adafruit_GFX so you should find it is working now.

Thanks for reporting this.
