### ISSUE TITLE
compatibility with TFT_eSPI for esp 66

### ISSUE THREAD

**Issue by ersivv** [Bodmer/JPEGDecoder#38]
Please add in JPEGDecoder.h for compatibility with TFT_eSPI for esp8266 in PlatformIO

#ifndef USER_SETUP_LOADED //  Lets PlatformIO users define settings in platformio.ini
	#include "User_Config.h"
#endif // USER_SETUP_LOADED

Example https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setup_Select.h

**Comment by Bodmer** [comment]
Added #ifndef JPEGDECODER_SETUP_LOADED to avoid conflict with TFT_eSPI settings.
