### ISSUE TITLE
Specific folder 

### ISSUE THREAD

**Issue by tarbear123** [Bodmer/JPEGDecoder#43]
How do you read a folder the the jpeg is in?
// open the image file File jpgFile = SD.open( "arduino.jpg", FILE_READ);

**Comment by Bodmer** [comment]
That is an SD library function. [Info can be found here](https://www.arduino.cc/en/Reference/SD).

You should be able to use a line like:
```
File jpgFile = SD.open( "folder/arduino.jpg", FILE_READ);
```
