### ISSUE TITLE
ESP8266 SD library woes

### ISSUE THREAD

**Issue by themakerbro** [Bodmer/JPEGDecoder#44]
On a clean install (version 1.8.9) using an ESP8266 board I get this error:

```
Sd2PinMap.h:524:2: error: #error Architecture or board not supported.
 #error Architecture or board not supported
```

I'm using code that's worked fine in the past. I even tried to simply run the SPIFFS example (obviously installing your TFT_eSPI library) to no avail. Any advise?

**Comment by Bodmer** [comment]
Try running just the SD library examples. Do they work?

**Comment by Bodmer** [comment]
See [this post](https://forum.arduino.cc/index.php?topic=609837.0) and discussion.

**Comment by Bodmer** [comment]
Assumed to be resolved.
