### ISSUE TITLE
Please add library.json and library.properties files to your repo

### ISSUE THREAD

**Issue by squix78** [Bodmer/JPEGDecoder#5]
Can you please add library.json and library.properties files to your repository? This allows them to be available through the library manager in the arduino IDE and the platform io lib manager.

See this documentations:
http://docs.platformio.org/en/latest/librarymanager/config.html
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification

Once you have added the files the platformio and arduino ide teams need to be asked to add your repository to their scanning job...

And here two examples:
https://github.com/squix78/esp8266-oled-ssd1306/blob/master/library.json
https://github.com/squix78/esp8266-oled-ssd1306/blob/master/library.properties

**Comment by Bodmer** [comment]
OK,  will do, thanks.

**Comment by Bodmer** [comment]
OK, I have added the files.

Thanks.

**Comment by squix78** [comment]
Thanks a lot! I think for the library managers to pick up the library files you'll also have to do a release here on github...

**Comment by Bodmer** [comment]
OK, thanks again.
