### ISSUE TITLE
Distorted JPEG Image 

### ISSUE THREAD

**Issue by lcfelippe** [Bodmer/JPEGDecoder#50]
Hi @Bodmer,

I´m trying to load some Jpeg images using the JPEG Decoder, Adafruit ILI9341 and Adafruit GFX Libraries. All images appears distorted at the right side. What could be wrong?

Hardware:
ESP32 + ILI9341

thanks.

Regards,

lcfelippe.

**Comment by Bodmer** [comment]
Check you are using the latest sketch code.

How many pixels wide is the image you wish to render, and how many pixels wide is the screen?

**Comment by lcfelippe** [comment]
Screen 320x240, the icon have 50x50 pixels

**Comment by Bodmer** [comment]
I suspect you are using old example code. Use the latest version examples as the starting point for your code or ensure the image width and height are an exact multiple of 8.
