### ISSUE TITLE
using my own pictures

### ISSUE THREAD

**Issue by tarbear123** [Bodmer/JPEGDecoder#52]
can I rename  "arduino.jpg", FILE_READ to the file my pictures are in?
also, can I replace  if (SD.exists("arduino.jpg"))  with my folder my picture are in

**Comment by tarbear123** [comment]
> can I rename "arduino.jpg", FILE_READ to the file my pictures are in?
> also, can I replace if (SD.exists("arduino.jpg")) with my folder my picture are in

hello?

**Comment by Bodmer** [comment]
You can rename files. The decoder library needs to be provided with file names of the jpeg files to decode. Check the SD library documentation, the "exists" function is not part of the JPEGDecoder library.
