### ISSUE TITLE
JPEGDecoder.h does not compile

### ISSUE THREAD

**Issue by bperrybap** [Bodmer/JPEGDecoder#8]
On operating systems that do not neuter filenames (i.e linux), JPEGDecoder.h will generate a compile error as it looks for "arduino.h" which does not exist.
In fact the include for "arduino.h" on line 23 does not seem to be necessary at all.

**Comment by Bodmer** [comment]
Thanks for pointing this out. I have deleted the #include in the repository copy.

**Comment by Bodmer** [comment]
Ah! Should have read Arduino.h, so arduino.h was a typo but Windows did not notice the letter case error.
